# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d38dab0c1a5c110a3d47c9aaa708b383dfbf7f298f5af7c4eb94c462d69c2031580044e504f6331e89f89a4d5b79f99e47ff91bcf64c562739edc0cf3ca21d7e

test:
  secret_key_base: 407247fb731c0bad33f6837107f8e008857c90e595505600ad7b82a15e89875919ad6b192450b660f4a3d37b48ac51b25201e7c22fe74e037f8e54e1f52ee15d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
